# Generated by Django 4.2.6 on 2023-10-17 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nombre Apuestas')),
                ('date_start', models.DateTimeField(verbose_name='Fecha Inicio')),
                ('date_end', models.DateTimeField(verbose_name='Fecha Fin')),
                ('state', models.CharField(max_length=1, verbose_name='Estado')),
                ('price', models.PositiveBigIntegerField(verbose_name='Precio')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.category', verbose_name='Categoría')),
                ('first_winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Primer Ganador')),
            ],
            options={
                'verbose_name': 'Rifa',
                'verbose_name_plural': 'Rifas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nombre Apuestas')),
                ('date_start', models.DateTimeField(verbose_name='Fecha Inicio')),
                ('date_end', models.DateTimeField(verbose_name='Fecha Fin')),
                ('state', models.CharField(max_length=1, verbose_name='Estado')),
                ('result', models.CharField(max_length=150, verbose_name='Resultado')),
                ('price_min', models.PositiveBigIntegerField(verbose_name='Precio Minimo')),
                ('price_max', models.PositiveBigIntegerField(verbose_name='Precio Maximo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.category', verbose_name='Categoría')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ganador')),
            ],
            options={
                'verbose_name': 'Apuesta',
                'verbose_name_plural': 'Apuestas',
                'ordering': ['-created'],
            },
        ),
    ]
