# Generated by Django 4.2.6 on 2023-10-26 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ganador', to=settings.AUTH_USER_MODEL, verbose_name='Ganador'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='first_winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganador', to=settings.AUTH_USER_MODEL, verbose_name='Primer Ganador'),
        ),
    ]
